sudo: false
language: r
cache: packages
warnings_are_errors: true

r:
  - 3.4.0 
  - 3.3.2

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

services:
  - mysql

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - Rscript -e "capabilities()"
  - mysql -e "create database IF NOT EXISTS TestdbUpdateTable;" -uroot
  - printf "[dbUpdateTable]\nusername=travis\ndatabase=TestdbUpdateTable\nhost=localhost\n" > ~/.my.cnf
